=== glittle/TallyJ-3.0/Site/Views/menu.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="root">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="menu" maxOccurs="unbounded">
          <xs:complexType>
            <xs:sequence maxOccurs="unbounded">
              <xs:choice>
                <xs:element ref="group"></xs:element>
                <xs:element ref="page"></xs:element>
              </xs:choice>
            </xs:sequence>
            <xs:attribute name="id" type="xs:string" use="required" />
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="group" type="group"/>
  <xs:element name="page" type="page"/>
  <xs:complexType name="group">
    <xs:sequence>
      <xs:sequence maxOccurs="unbounded">
        <xs:choice>
          <xs:element ref="group"></xs:element>
          <xs:element ref="page"></xs:element>
        </xs:choice>
      </xs:sequence>
    </xs:sequence>
    <xs:attribute name="title" type="xs:string" use="required" />
    <xs:attribute name="longtitle" type="xs:string" use="required" />
    <xs:attribute name="state" type="xs:string" use="required" />
    <xs:attribute name="showTitleInPage" type="xs:boolean" use="optional" />
    <xs:attribute name="isPreBallot" type="xs:boolean" use="optional" />
  </xs:complexType>
  <xs:complexType name="page">
    <xs:attribute name="title" type="xs:string" use="required" />
    <xs:attribute name="controller" type="xs:string" use="required" />
    <xs:attribute name="action" type="xs:string" use="required" />
    <xs:attribute name="class" type="xs:string" use="optional" />
    <xs:attribute name="role" type="xs:string" use="required" />
    <xs:attribute name="desc" type="xs:string" use="required" />
    <xs:attribute name="featureWhen" type="xs:string" use="optional" />
    <xs:attribute name="requireElection" type="xs:boolean" use="required" />
    <xs:attribute name="requireProcess" type="xs:string" use="optional" />
    <xs:attribute name="hideForTypes" type="xs:string" use="optional" />
    <xs:attribute name="onlyForTypes" type="xs:string" use="optional" />
    <xs:attribute name="showOnDashboard" type="xs:boolean" use="optional" />
    <xs:attribute name="showInOtherList" type="xs:boolean" use="optional" />
    <xs:attribute name="showLocationSelector" type="xs:boolean" use="optional" />
    <xs:attribute name="showLocationSelectorWithOnline" type="xs:boolean" use="optional" />
    <xs:attribute name="showTellerSelector" type="xs:boolean" use="optional" />
    <xs:attribute name="isPreBallot" type="xs:boolean" use="optional" />
    <xs:attribute name="hasTies" type="xs:boolean" use="optional" />
  </xs:complexType>

</xs:schema>

=== glittle/TallyJ-3.0/Site/Views/menu.xml
<?xml version="1.0" encoding="utf-8" ?>
<root  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="menu.xsd">
  <menu id="main">
    <group title="Preparing" state="NotStarted" longtitle="Setting Up - Preparing for the election" showTitleInPage="false">
      <!--<page title="Set Mode" controller="Setup" action="Index2" requireElection="true" role="known" desc="Set election mode to X"></page>-->
      <page title="Configure this Election" featureWhen="NotStarted" controller="Setup" action="Index" requireElection="true" role="known" desc="Select type of election and other details"></page>
      <page title="Import Name List" hideForTypes="LSAU" featureWhen="NotStarted" controller="Setup" action="ImportCsv" requireElection="true" role="known" desc="Upload and import names of people from CSV files"></page>
      <!--<page title="Import Version 1" showOnDashboard="false" controller="Setup" action="ImportV1" requireElection="true" role="known" desc="Upload and import files from TallyJ version 1.8x"></page>-->
      <page title="Edit People's Names" featureWhen="NotStarted" controller="Setup" action="People" requireElection="true" role="known" desc="Edit people's names. Add more people."></page>
      <page title="Send Notifications" featureWhen="OnDash,NotStarted" controller="Setup" action="Notify" requireElection="true" role="known" desc="Send email or text notifications"></page>
    </group>
    <group title="Voting" state="NamesReady" longtitle="Gathering Ballots - Registration and Voting" showTitleInPage="false">
      <page title="Front Desk" featureWhen="NamesReady" showTellerSelector="true" showLocationSelector="true" controller="Before" action="FrontDesk" requireElection="true" role="guest" desc="Welcome voters to the election venue. Record who is participating in the election." isPreBallot="true"></page>
      <page title="Sort Envelopes" featureWhen="NamesReady" requireProcess="Roll" controller="Ballots" showLocationSelector="true" action="SortBallots" requireElection="true" role="guest" desc="Show sorted list of ballot envelopes received." isPreBallot="true"></page>
      <page title="Roll Call" class="Projector" featureWhen="NamesReady" requireProcess="Roll" controller="Before" action="RollCall" requireElection="true" role="guest" desc="Display the names of those who are voting." isPreBallot="true" ></page>
      <page title="Count Envelopes" featureWhen="NamesReady" controller="Ballots" showLocationSelector="true" action="Reconcile" requireElection="true" role="guest" desc="Review the number of ballot envelopes received from each source." isPreBallot="true" ></page>
    </group>
    <group title="Tallying" state="Tallying" longtitle="Processing Ballots - Tallying and Analyzing" showTitleInPage="false">
      <page title="Monitor Progress"  featureWhen="Tallying" controller="After" action="Monitor" requireElection="true" role="guest" desc="Centrally monitor progress of tellers."></page>
      <page title="Enter Ballots"  featureWhen="Tallying" showTellerSelector="true" showLocationSelectorWithOnline="true" controller="Ballots" action="Index" requireElection="true" role="guest" desc="Type in the names found on ballots."></page>
      <page title="Import External Ballots"  featureWhen="Tallying" controller="Setup" action="ImportBallots" requireElection="true" role="known" desc="Import ballots collected via an external source or method."></page>
      <page title="Analyze Ballots"  featureWhen="Tallying,Finalized" controller="After" action="Analyze" requireElection="true" role="known" desc="Review results, checking for ties."></page>
      
      <page title="View Reports"  featureWhen="Tallying,Finalized" controller="After" action="Reports" requireElection="true" role="guest" desc="Generate election reports."></page>

      <page title="Display Tie-Breaks"  featureWhen="Tallying" class="Projector" controller="After" action="ShowTies" requireElection="true" role="guest" desc="Show tie-break information." hasTies="true"></page>
      <page title="Display Tellers' Report"  featureWhen="Finalized" class="Projector" controller="After" action="Presenter" requireElection="true" role="guest" desc="Display results of the election."></page>
    </group>
    <group title="general" state="" longtitle="Other Pages" showTitleInPage="false">
      <page title="Welcome Page" featureWhen="OnDash" controller="Public" action="Index" showOnDashboard="false" requireElection="false" role="*" desc="Welcome page"></page>
      <page title="Elections List" featureWhen="OnDash, General" controller="Dashboard" action="ElectionList" requireElection="false" role="known" desc="List your elections.  Choose, save, load and delete elections."></page>
      <page title="Sys Logs" controller="SysAdmin" action="Index" requireElection="false" role="sysAdmin" desc="View Sys Admin logs."></page>
      <page title="Dashboard" featureWhen="OnDash, General" controller="Dashboard" action="Index" showOnDashboard="false" showInOtherList="true" requireElection="true" role="*" desc="A listing of all the modules and pages in TallyJ"></page>
      <page title="Reference Materials" featureWhen="OnDash, General" controller="Public" action="Learning" requireElection="false" role="*" desc="Read more about Bahá’í elections, the job of tellers, and how TallyJ works."></page>
      <page title="Change my Password" featureWhen="OnDash, General" controller="Account" action="ChangePassword" requireElection="true" role="known" desc="Change your password"></page>
      <page title="Logout" featureWhen="OnDash, General" controller="Account" action="Logoff" showOnDashboard="true" requireElection="false" role="guest" desc="Log out of the site"></page>
    </group>
  </menu>
  <menu id="misc">
    <page title="Logon Page" controller="Account" action="LogOn" requireElection="false" role="*" desc=""/>
    <page title="Register Page" controller="Account" action="Register" requireElection="false" role="*" desc=""/>
    <page title="Contact" controller="Public" featureWhen="General" action="Contact" requireElection="false" role="*" desc=""/>
    <page title="About" controller="Public" action="About" requireElection="false" role="*" desc=""/>
    <page title="Install" controller="Public" action="Install" requireElection="false" role="*" desc=""/>
  </menu>
</root>
